### ISSUE TITLE
Save lights mode  to storage or to URL

### ISSUE THREAD

**Issue by JarisGV** [theWildSushii/Koilors#1]
Hey guys.

When I choose dark mode, every time I refresh the page it goes back to light mode. Sometimes the color palette we choose is best displayed with a dark theme. So I would like to know how to save the selected theme in localStorage or, better yet, save it in the URL, in this case I would be able to share the color palette directly with the best background theme.

For example, if I could send light mode to the URL, the final URL would be **_koilors.com/#e5426f/tetrar/4/22.7/93.2/63.54/dm_** where dm means dark mode or **_koilors.com/#e5426f/ tetrar/4/22.7/93.2/63.54/lm where lm_** means light mode.

It's possible?

Thank you in advance

Jaris GV

**Comment by theWildSushii** [comment]
Hello!

Currently, Koilors uses the browser's preferred light mode as the default light mode. There's currently no way of saving it into the URL or storage and thus it resets every time you open Koilors.

However, your suggestion is actually a pretty good one and I'll take a look into it to implement it without breaking compatibility to the previous saved data.

I'll let you know here when it's implemented, which shouldn't take long 😉

**Comment by JarisGV** [comment]
Thank you so much

**Comment by theWildSushii** [comment]
The update is live!

You can now freely share a palette including its light mode.

Previously saved palettes (URLs and localStorage) use the browser's preferred light mode as a fallback.

**Comment by JarisGV** [comment]
Thanks a lot 🙏🏽🙏🏽🙏🏽

**Comment by theWildSushii** [comment]
I'll close this issue now 😊
